headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
  Accept-Language: "en-US,en;q=0.9"
  Referer: "https://www.google.com/"
  DNT: "1"

request:
  timeout: 10
  retry:
    total: 3
    status_forcelist: [429, 500, 502, 503, 504]
    allowed_methods: ["GET"]
    backoff_factor: 1

selectors:
  default: '[class*="ingredient"], .ingredients li'
  sites:
    allrecipes.com: '.ingredients-item-name'
    recipetineats.com: '.wprm-recipe-ingredient-name'

model:
  temp: 0.1
  